// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://iiimpsfjzcgxcoxvveis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_ijl_h-HSSVhvLNv5zWV5Tg_jrxhbX41";

// Create a dummy storage for SSR to prevent errors
const isBrowser = typeof window !== 'undefined';
const dummyStorage = {
  getItem: () => null,
  setItem: () => {},
  removeItem: () => {},
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.sessionStorage : dummyStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: isBrowser,
  }
});

console.log("SUPABASE INITIALIZED:", !!supabase, "AUTH:", !!supabase?.auth);